import { Link, useParams } from "react-router-dom";
import { ArrowLeft, ArrowRight, Leaf } from "lucide-react";
import { legalPages } from "@/data/siteData";

export default function Legal() {
  const { slug } = useParams();
  const page = legalPages.find((item) => item[1] === slug);
  const title = page?.[0] || "Website policy";
  return <div className="min-h-screen bg-cream text-forest-950"><header className="border-b border-forest-950/10 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Link to="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-forest-700 text-sand-300"><Leaf size={18} fill="currentColor" /></span><span className="text-sm font-extrabold tracking-[0.12em]">EARTH ROOT <span className="text-forest-700">AGRO</span></span></Link><Link to="/" className="text-sm font-semibold text-forest-700">Back to home</Link></div></header><main className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="grid gap-16 lg:grid-cols-[0.7fr_1.3fr]"><aside><p className="eyebrow">Legal & policies</p><h1 className="section-title mt-5">{title}</h1><Link to="/" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-forest-700"><ArrowLeft size={15} /> Home</Link><div className="mt-12 hidden border-t border-forest-950/10 pt-5 lg:block"><p className="mb-4 text-xs font-bold uppercase tracking-[0.15em] text-forest-950/45">All policies</p><div className="grid gap-2">{legalPages.slice(0, 12).map(([label, value]) => <Link key={value} to={`/legal/${value}`} className={`text-sm ${value === slug ? "font-bold text-forest-700" : "text-forest-950/55 hover:text-forest-700"}`}>{label}</Link>)}</div></div></aside><article className="max-w-3xl rounded-3xl bg-white p-7 shadow-[0_15px_50px_rgba(24,61,42,0.06)] sm:p-10 lg:p-14"><p className="text-sm text-forest-950/45">Last updated: 1 January 2025</p><div className="mt-10 space-y-9 text-sm leading-8 text-forest-950/65"><section><h2 className="font-display text-3xl text-forest-950">Our commitment</h2><p className="mt-3">Earth Root Agro is committed to conducting agricultural trade with clarity, care and respect. This {title.toLowerCase()} explains the standards and expectations that apply when you use our website or work with our team.</p></section><section><h2 className="font-display text-3xl text-forest-950">How this applies</h2><p className="mt-3">We use clear processes for enquiries, quotations, sourcing, documentation and delivery. Information is handled only for legitimate business communication, service improvement and fulfilling agreed requirements.</p></section><section><h2 className="font-display text-3xl text-forest-950">Questions or concerns</h2><p className="mt-3">For clarification about this policy or any Earth Root Agro business practice, contact our team at <a href="mailto:rajshekharallam786@gmail.com" className="font-semibold text-forest-700">rajshekharallam786@gmail.com</a> or call +91 96196 31768.</p></section></div><Link to="/contact" className="mt-12 inline-flex items-center rounded-full bg-forest-700 px-6 py-4 text-sm font-bold text-white">Contact our team <ArrowRight className="ml-2" size={16} /></Link></article></div></main></div>;
}
