import { ArrowRight, Factory, Globe2, MapPin, PackageCheck, Users } from "lucide-react";
import { Link } from "react-router-dom";

export default function HomeAdditions() {
  return <>
    <section className="bg-white py-24 lg:py-32">
      <div className="mx-auto max-w-7xl px-5 lg:px-8">
        <div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-end">
          <div><p className="eyebrow">Where we create value</p><h2 className="section-title mt-5">Made for the<br /><span>people who feed us.</span></h2></div>
          <p className="max-w-lg leading-7 text-forest-950/60">Whether you are a food manufacturer, a retail chain or an exporter, our sourcing network is designed around the realities of your business.</p>
        </div>
        <div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {[[Factory, "Food makers", "Consistent ingredients for processing and production."], [Users, "Retail & hospitality", "Reliable supply for hotels, restaurants and stores."], [Globe2, "Export houses", "India-origin commodities prepared for global trade."], [PackageCheck, "Bulk buyers", "Commercial quantities, clear specs and fair pricing."]].map(([Icon, title, body], index) => <div key={title as string} className={`rounded-2xl p-6 ${index % 2 ? "bg-sand-200" : "bg-cream"}`}><Icon className={index % 2 ? "text-forest-700" : "text-sand-300"} size={24} /><h3 className="mt-8 font-display text-2xl">{title as string}</h3><p className="mt-2 text-sm leading-6 text-forest-950/55">{body as string}</p></div>)}
        </div>
      </div>
    </section>
    <section className="bg-sand-200 py-24 lg:py-32">
      <div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[1.05fr_0.95fr] lg:items-center lg:px-8">
        <div className="relative overflow-hidden rounded-[28px]"><img src="https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=1300&q=85" alt="Agricultural warehouse logistics" className="aspect-[1.15] h-full w-full object-cover" /><div className="absolute bottom-5 left-5 right-5 rounded-2xl border border-white/30 bg-forest-950/65 p-5 text-white backdrop-blur-md"><div className="flex items-center gap-3"><MapPin className="text-sand-300" size={20} /><span className="text-sm">Coordinated from Mumbai, delivered worldwide</span></div></div></div>
        <div><p className="eyebrow">Beyond the border</p><h2 className="section-title mt-5">India to the<br /><span>world's table.</span></h2><p className="mt-7 leading-7 text-forest-950/65">Our export desk brings together product knowledge, documentation support and dependable dispatch planning so international buyers can source with confidence.</p><div className="mt-8 grid grid-cols-2 gap-5 border-t border-forest-950/15 pt-7"><div><p className="font-display text-4xl text-forest-700">12+</p><p className="mt-1 text-xs uppercase tracking-[0.12em] text-forest-950/50">Trade corridors</p></div><div><p className="font-display text-4xl text-forest-700">48h</p><p className="mt-1 text-xs uppercase tracking-[0.12em] text-forest-950/50">Quote response</p></div></div><Link to="/contact" className="mt-8 inline-flex items-center gap-2 text-sm font-bold uppercase tracking-[0.12em] text-forest-700">Plan an export order <ArrowRight size={16} /></Link></div>
      </div>
    </section>
    <section className="bg-forest-950 py-24 text-white lg:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow text-sand-300">A growing network</p><h2 className="section-title mt-5 text-white">Numbers with<br /><em className="text-sand-300">meaning behind them.</em></h2></div><p className="max-w-sm text-sm leading-7 text-white/55">Every number reflects a relationship, a shipment or a promise kept.</p></div><div className="mt-14 grid gap-8 border-y border-white/15 py-10 sm:grid-cols-2 lg:grid-cols-4">{[["44", "Product lines"], ["18", "Growing regions"], ["100%", "Buyer-focused"], ["2025", "Founded in Mumbai"]].map(([number, label]) => <div key={label}><p className="font-display text-5xl text-sand-300">{number}</p><p className="mt-3 text-xs uppercase tracking-[0.14em] text-white/55">{label}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow">From the field</p><h2 className="section-title mt-5">Useful thinking for<br /><span>better buying.</span></h2></div><Link to="/contact" className="inline-flex items-center gap-2 text-sm font-bold uppercase tracking-[0.12em] text-forest-700">Talk to a sourcing expert <ArrowRight size={16} /></Link></div><div className="mt-14 grid gap-5 md:grid-cols-3">{[["Trade guide · 06 min", "Buying pulses in bulk: what to check first", "A practical look at grade, moisture, packing and the questions that protect your supply."], ["Export note · 04 min", "What makes an export-ready commodity?", "From documentation to dispatch, the details that make international supply smoother."], ["Origin story · 03 min", "Why relationships are our real infrastructure", "Good sourcing is built on people who know the crop, the season and the destination."]].map(([meta, title, body]) => <article key={title} className="border-t border-forest-950/15 pt-5"><p className="text-xs font-bold uppercase tracking-[0.15em] text-sand-300">{meta}</p><h3 className="mt-5 font-display text-3xl">{title}</h3><p className="mt-4 text-sm leading-7 text-forest-950/55">{body}</p><Link to="/contact" className="mt-6 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-forest-700">Read more <ArrowRight size={14} /></Link></article>)}</div></section>
  </>;
}
